export const dummyCategories = [
  { _id: 'cat-1', name: 'Car Accessories', slug: 'car-accessories', isActive: true },
  { _id: 'cat-2', name: 'Car Care', slug: 'car-care', isActive: true },
  { _id: 'cat-3', name: 'Electronics', slug: 'electronics', isActive: true },
  { _id: 'cat-4', name: 'Interior', slug: 'interior', isActive: true },
  { _id: 'cat-5', name: 'Collectibles', slug: 'collectibles', isActive: true },
  { _id: 'cat-6', name: 'Cooling & Comfort', slug: 'cooling-comfort', isActive: true },
];

export const dummyProducts = [
  {
    _id: 'p1',
    name: 'Quick Charge 3.0 Car Charger – 3-in-1 Cable',
    slug: 'quick-charge-car-charger-3in1',
    sku: 'RSA-001',
    description: 'Fast charging car charger with QC 3.0 support. Comes with 3-in-1 braided cable (Lightning, USB-C, Micro USB). Universal compatibility.',
    shortDescription: 'QC 3.0 car charger with 3-in-1 cable',
    price: 899,
    discountPrice: 699,
    category: { _id: 'cat-3', name: 'Electronics', slug: 'electronics' },
    brand: 'RS Automart',
    images: [{ url: '/products/car-charger.png', publicId: 's1' }],
    stock: { quantity: 50, status: 'in_stock' },
    tags: ['car charger', 'quick charge', 'usb', '3 in 1'],
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    warranty: '6 Months Warranty',
    ratings: { average: 4.5, count: 42 },
    totalSold: 185,
    createdAt: '2026-03-20',
  },
  {
    _id: 'p2',
    name: 'Diecast Jeep Wrangler Model – 1:32 Scale (White)',
    slug: 'diecast-jeep-wrangler-white',
    sku: 'RSA-002',
    description: 'Premium diecast Jeep Wrangler model car. 1:32 scale, pull-back action, opening doors. Perfect for car enthusiasts and collectors.',
    shortDescription: '1:32 scale Jeep Wrangler diecast model',
    price: 1299,
    discountPrice: 999,
    category: { _id: 'cat-5', name: 'Collectibles', slug: 'collectibles' },
    brand: 'RS Automart',
    images: [{ url: '/products/diecast-jeep.png', publicId: 's2' }],
    stock: { quantity: 20, status: 'in_stock' },
    tags: ['diecast', 'model car', 'jeep', 'collectible'],
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    warranty: '7 Days Replacement',
    ratings: { average: 4.7, count: 28 },
    totalSold: 95,
    createdAt: '2026-03-28',
  },
  {
    _id: 'p3',
    name: 'Car Console Organizer – Leather with Cup Holder',
    slug: 'car-console-organizer-leather',
    sku: 'RSA-003',
    description: 'Premium PU leather console organizer with tissue box, cup holders, and card slots. Fits between car seats.',
    shortDescription: 'Leather console organizer with cup holders',
    price: 1599,
    discountPrice: 1199,
    category: { _id: 'cat-4', name: 'Interior', slug: 'interior' },
    brand: 'RS Automart',
    images: [{ url: '/products/console-organizer.png', publicId: 's3' }],
    stock: { quantity: 35, status: 'in_stock' },
    tags: ['organizer', 'console', 'leather', 'interior'],
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: true,
    warranty: '30 Days Return',
    ratings: { average: 4.3, count: 56 },
    totalSold: 220,
    createdAt: '2026-03-15',
  },
  {
    _id: 'p4',
    name: 'Colum Air Spencer Car Air Freshener – Premium',
    slug: 'colum-air-spencer-freshener',
    sku: 'RSA-004',
    description: 'Japanese Colum Air Spencer premium car air freshener. Long-lasting fragrance, elegant dashboard design.',
    shortDescription: 'Premium Japanese car air freshener',
    price: 1899,
    discountPrice: 1499,
    category: { _id: 'cat-4', name: 'Interior', slug: 'interior' },
    brand: 'Air Spencer',
    images: [{ url: '/products/air-freshener.png', publicId: 's4' }],
    stock: { quantity: 15, status: 'in_stock' },
    tags: ['air freshener', 'car perfume', 'interior', 'air spencer'],
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    warranty: '7 Days Replacement',
    ratings: { average: 4.6, count: 34 },
    totalSold: 145,
    createdAt: '2026-02-10',
  },
  {
    _id: 'p5',
    name: 'Luxury Car Fragrance Gift Set – Gold Edition',
    slug: 'luxury-car-fragrance-gold',
    sku: 'RSA-005',
    description: 'Premium car fragrance gift set with gold bullion design. Solar-powered rotating base. Luxury gift box packaging.',
    shortDescription: 'Gold edition luxury car fragrance set',
    price: 2499,
    discountPrice: 1899,
    category: { _id: 'cat-4', name: 'Interior', slug: 'interior' },
    brand: 'RS Automart',
    images: [{ url: '/products/car-fragrance.png', publicId: 's5' }],
    stock: { quantity: 8, status: 'in_stock' },
    tags: ['fragrance', 'luxury', 'gift', 'gold'],
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    warranty: '15 Days Return',
    ratings: { average: 4.8, count: 18 },
    totalSold: 62,
    createdAt: '2026-04-01',
  },
  {
    _id: 'p6',
    name: 'Portable Car Vacuum Cleaner – Handheld Powerful',
    slug: 'portable-car-vacuum-cleaner',
    sku: 'RSA-006',
    description: 'Powerful handheld car vacuum cleaner with 6000PA suction. Cordless, USB rechargeable. Compact nozzle for tight spaces.',
    shortDescription: 'Cordless handheld car vacuum, 6000PA',
    price: 1999,
    discountPrice: 1499,
    category: { _id: 'cat-2', name: 'Car Care', slug: 'car-care' },
    brand: 'RS Automart',
    images: [{ url: '/products/car-vacuum.png', publicId: 's6' }],
    stock: { quantity: 25, status: 'in_stock' },
    tags: ['vacuum', 'car cleaner', 'portable', 'cordless'],
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: true,
    warranty: '6 Months Warranty',
    ratings: { average: 4.4, count: 47 },
    totalSold: 178,
    createdAt: '2026-03-25',
  },
  {
    _id: 'p7',
    name: 'DTR Glass Cleaner Spray – Streak Free (500ml)',
    slug: 'dtr-glass-cleaner-spray',
    sku: 'RSA-007',
    description: 'Professional grade glass cleaner spray. Streak-free formula for windshields, mirrors, and windows. 500ml bottle.',
    shortDescription: 'Streak-free glass cleaner, 500ml',
    price: 399,
    discountPrice: 299,
    category: { _id: 'cat-2', name: 'Car Care', slug: 'car-care' },
    brand: 'DTR',
    images: [{ url: '/products/glass-cleaner.png', publicId: 's7' }],
    stock: { quantity: 100, status: 'in_stock' },
    tags: ['glass cleaner', 'spray', 'windshield', 'car care'],
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
    warranty: '30 Days Return',
    ratings: { average: 4.2, count: 65 },
    totalSold: 340,
    createdAt: '2026-01-20',
  },
  {
    _id: 'p8',
    name: 'Car Seat Cooling Fan – TK1500 Headrest Mount',
    slug: 'car-seat-cooling-fan-tk1500',
    sku: 'RSA-008',
    description: 'Car seat cooling fan that mounts on headrest. 3-speed USB powered. Keeps back cool during summer drives.',
    shortDescription: 'Headrest mount seat cooling fan, USB',
    price: 1799,
    discountPrice: 1399,
    category: { _id: 'cat-6', name: 'Cooling & Comfort', slug: 'cooling-comfort' },
    brand: 'RS Automart',
    images: [{ url: '/products/seat-cooling-fan.png', publicId: 's8' }],
    stock: { quantity: 18, status: 'in_stock' },
    tags: ['cooling fan', 'car seat', 'summer', 'usb fan'],
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    warranty: '6 Months Warranty',
    ratings: { average: 4.1, count: 22 },
    totalSold: 73,
    createdAt: '2026-03-30',
  },
  {
    _id: 'p9',
    name: 'Royal Mazeda Foaming Shampoo – Car & Bike (550ml)',
    slug: 'royal-mazeda-foaming-shampoo',
    sku: 'RSA-009',
    description: 'Max foaming car & bike wash shampoo. Advanced cleaning with shine & protection. 550ml bottle.',
    shortDescription: 'Max foaming car wash shampoo, 550ml',
    price: 599,
    discountPrice: 449,
    category: { _id: 'cat-2', name: 'Car Care', slug: 'car-care' },
    brand: 'Royal Mazeda',
    images: [{ url: '/products/foaming-shampoo.png', publicId: 's9' }],
    stock: { quantity: 80, status: 'in_stock' },
    tags: ['shampoo', 'car wash', 'foaming', 'bike wash'],
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: true,
    warranty: '30 Days Return',
    ratings: { average: 4.5, count: 53 },
    totalSold: 290,
    createdAt: '2026-03-18',
  },
  {
    _id: 'p10',
    name: 'Double Engine Car Fan – F303 Silicone Hose',
    slug: 'double-engine-car-fan-f303',
    sku: 'RSA-010',
    description: 'Dual head car cooling fan with flexible silicone hose. USB powered, 3-speed, 360° adjustable. TK1600 model.',
    shortDescription: 'Dual head USB car fan, 360° rotation',
    price: 1499,
    discountPrice: 1099,
    category: { _id: 'cat-6', name: 'Cooling & Comfort', slug: 'cooling-comfort' },
    brand: 'RS Automart',
    images: [{ url: '/products/double-fan.png', publicId: 's10' }],
    stock: { quantity: 30, status: 'in_stock' },
    tags: ['car fan', 'cooling', 'dual fan', 'usb'],
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    warranty: '6 Months Warranty',
    ratings: { average: 4.3, count: 38 },
    totalSold: 156,
    createdAt: '2026-02-25',
  },
  {
    _id: 'p11',
    name: 'Diecast Classic BMW 501 Model – 1:32 Scale (Blue)',
    slug: 'diecast-bmw-501-classic-blue',
    sku: 'RSA-011',
    description: 'Premium diecast BMW 501 classic car model. 1:32 scale with pull-back action. Deep blue metallic finish.',
    shortDescription: '1:32 BMW 501 classic diecast model',
    price: 1399,
    discountPrice: 1099,
    category: { _id: 'cat-5', name: 'Collectibles', slug: 'collectibles' },
    brand: 'RS Automart',
    images: [{ url: '/products/diecast-classic.png', publicId: 's11' }],
    stock: { quantity: 12, status: 'in_stock' },
    tags: ['diecast', 'model car', 'bmw', 'classic', 'collectible'],
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    warranty: '7 Days Replacement',
    ratings: { average: 4.6, count: 15 },
    totalSold: 48,
    createdAt: '2026-04-02',
  },
  {
    _id: 'p12',
    name: 'Bangladesh Flag Dashboard Stand – Solar Powered',
    slug: 'bangladesh-flag-dashboard-stand',
    sku: 'RSA-012',
    description: 'Dual Bangladesh flag stand for car dashboard. Solar powered rotating base with tire-shaped design. Show your pride!',
    shortDescription: 'Solar rotating BD flag dashboard stand',
    price: 499,
    discountPrice: 349,
    category: { _id: 'cat-1', name: 'Car Accessories', slug: 'car-accessories' },
    brand: 'RS Automart',
    images: [{ url: '/products/bd-flag-stand.png', publicId: 's12' }],
    stock: { quantity: 3, status: 'low_stock' },
    tags: ['flag', 'bangladesh', 'dashboard', 'patriotic'],
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    warranty: '7 Days Replacement',
    ratings: { average: 4.9, count: 72 },
    totalSold: 410,
    createdAt: '2026-03-26',
  },
];
